//
// Created by barriean on 08/06/2021.
//

#ifndef SKELETON_CONSTANTS_HPP
#define SKELETON_CONSTANTS_HPP


#define APPLICATION_WIDTH	700
#define APPLICATION_HEIGHT	600
#define WIDGET_PANEL_WIDTH	150
#define WIDGET_Y0			30
#define WIDGET_Y_STEP		50
#define WIDGET_Y_SECURE		120

#define APP_NAME "Svex Editors v1.0"

enum
{
    ID_QUIT = 1,
    ID_ABOUT,
    ID_LOAD,
    ID_SAVE,
    ID_SLIDER1,
    ID_SLIDER2,
    ID_CHECKBOX1,
    ID_CHECKBOX2,
    ID_CHECKBOX3,
    ID_RADIOBOX,
    ID_CLPICKER1,
    ID_CLPICKER2,
    ID_CHECKBOX4
};
#endif //SKELETON_CONSTANTS_HPP
